### lab 4-1 : multi-variable linear regression 을 tensorflow 에서 구현하기

$$ H(x_1, x_2, x_3) = x_1w_1 + x_2w_2 + x_3w_3$$

In [2]:
import tensorflow as tf

In [1]:
x1_data = [73, 93, 89, 97, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]

y_data = [152, 185, 180, 196, 142]


In [4]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [5]:
w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name= 'bias')

In [6]:
hypothesis  =  x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)

train = optimizer.minimize(cost)

sess = tf.Session()

In [15]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001) : 
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {x1 : x1_data, x2: x2_data, x3:x3_data, Y : y_data})
    if step % 10 == 0 :
        print(step, "Cost : ", cost_val, "\nprediction:\n", hy_val)


0 Cost :  19737.1 
prediction:
 [ 33.68896103  30.42724419  35.09645081  38.4000473   19.68694115]
10 Cost :  29.6338 
prediction:
 [ 157.74475098  179.57847595  182.03425598  198.95787048  133.46263123]
20 Cost :  29.3131 
prediction:
 [ 158.09449768  180.03657532  182.46601868  199.43392944  133.81991577]
30 Cost :  29.1685 
prediction:
 [ 158.07519531  180.05099487  182.46069336  199.43238831  133.83877563]
40 Cost :  29.0248 
prediction:
 [ 158.05485535  180.06407166  182.4540863   199.4294281   133.85655212]
50 Cost :  28.8819 
prediction:
 [ 158.03456116  180.07707214  182.44747925  199.4264679   133.87428284]
60 Cost :  28.7397 
prediction:
 [ 158.01434326  180.09007263  182.44091797  199.42353821  133.89198303]
70 Cost :  28.5982 
prediction:
 [ 157.99415588  180.10302734  182.43435669  199.42059326  133.90962219]
80 Cost :  28.4575 
prediction:
 [ 157.9740448   180.11595154  182.42781067  199.41767883  133.92723083]
90 Cost :  28.3175 
prediction:
 [ 157.95397949  180.1288147 

790 Cost :  20.1543 
prediction:
 [ 156.67518616  180.94975281  182.00572205  199.22622681  135.06614685]
800 Cost :  20.0583 
prediction:
 [ 156.65861511  180.9604187   182.00036621  199.22377014  135.08073425]
810 Cost :  19.9627 
prediction:
 [ 156.64207458  180.97102356  181.99497986  199.22129822  135.09527588]
820 Cost :  19.8677 
prediction:
 [ 156.62561035  180.98161316  181.98963928  199.21884155  135.10978699]
830 Cost :  19.7731 
prediction:
 [ 156.60916138  180.99215698  181.98429871  199.21636963  135.12425232]
840 Cost :  19.679 
prediction:
 [ 156.59274292  181.00270081  181.97897339  199.21391296  135.13867188]
850 Cost :  19.5855 
prediction:
 [ 156.5763855   181.01318359  181.97364807  199.2114563   135.15306091]
860 Cost :  19.4924 
prediction:
 [ 156.56007385  181.02366638  181.96836853  199.20903015  135.16741943]
870 Cost :  19.3998 
prediction:
 [ 156.54382324  181.03411865  181.96307373  199.20658875  135.18173218]
880 Cost :  19.3078 
prediction:
 [ 156.5275878

1620 Cost :  13.6834 
prediction:
 [ 155.44065857  181.74223328  181.60520935  199.0388031   136.15579224]
1630 Cost :  13.6214 
prediction:
 [ 155.42738342  181.75071716  181.60087585  199.03672791  136.16752625]
1640 Cost :  13.5598 
prediction:
 [ 155.41418457  181.75921631  181.59660339  199.03469849  136.179245  ]
1650 Cost :  13.4985 
prediction:
 [ 155.40101624  181.76768494  181.59233093  199.03265381  136.19093323]
1660 Cost :  13.4375 
prediction:
 [ 155.38783264  181.77610779  181.58805847  199.03059387  136.20257568]
1670 Cost :  13.3768 
prediction:
 [ 155.37472534  181.78451538  181.58380127  199.02856445  136.21420288]
1680 Cost :  13.3165 
prediction:
 [ 155.36167908  181.79292297  181.57958984  199.02656555  136.22581482]
1690 Cost :  13.2565 
prediction:
 [ 155.34861755  181.80128479  181.5753479   199.02452087  136.23735046]
1700 Cost :  13.1968 
prediction:
 [ 155.33561707  181.80963135  181.57113647  199.02250671  136.24890137]
1710 Cost :  13.1374 
prediction:
 [ 

#### 코드를 줄이기 위한 Matrix의 multiply 사용

### lab 4-2 : tensorflow 로 파일에서 데이터 읽어오기

comma로 나누어진 csv의 경우, 

#가장 간단한 경우
1. np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)  
(slicing, indexing에 대한 내용 - 빠른 skip)

![image.png](img/4-1.png)
- 파일이 너무 커서 메모리에 올리기도 부족할 경우가 있을 수 있음
- 텐서플로우에서 queue runner를 제공해줌.
- 여러개의 파일을 queue에다가 쌓게 되고, 이것을 Reader로 연결하여 decoder로 보내줘서 example queue로 쌓아올림, 학습에 필요한 데이터는 전체 데이터가 아니므로, 필요한 경우에만 꺼내 쓸 수 있게 해줌 . 굉장히 큰 데이터를 쓸 때 유용함. 

#queue runner 사용  
![image.png](img/4-2.png)
- 2. reader를 정의, binary로 읽는다든가
- 3. value를 읽어왔는데, value값을 어떻게 parsing 할 것인가?를 decode csv로 정의
> 읽어올 때, recorde_dafault를 통해 값을 정의 해줄 수 있음. 사진에선 float으로

![image.png](img/4-3.png)
- 이 값을 텐서플로의 배치를 가지고 읽어오게 됨. 일종의 펌프 역할을 해서 읽어올 수 있게 해줌
- coordinator은 통상적으로 사용하는 부분이라고 인식하면 됨. 

shuffle batch - 배치의 순서를 섞을 수 있음.